version: '3.5'

services:
  kotlini-restful-api-postgres:
    container_name: "kotlin-restful-api-postgres"
    image: postgres:14-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: kotlin
      POSTGRES_USER: kotlin
      POSTGRES_DB: restful-api